#!/usr/bin/env bash
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"


print_help() {
  echo "Usage: $0 [options]"
  echo "Options:"
  echo "  -c              Clean build directory and rebuild"
  echo "  -r              Build in release mode"
  echo "  -h              Show this help message"
}

# script options
CMAKE_OPTIONS=("CMAKE_BUILD_TYPE")
BUILD_OPTIONS=()

CMAKE_BUILD_TYPE="Debug"
CLEAN=OFF

while getopts "crshv:" opt; do
  case "$opt" in
  c)
    echo "Clean build directory and rebuild"
    CLEAN=ON
    ;;
  r)
    echo "Building in release mode"
    CMAKE_BUILD_TYPE="Release"
    ;;
  h)
    print_help
    exit 0
    ;;
  *)
    echo "Invalid option" >&2
    print_help
    exit 1
    ;;
  esac
done

# construct CMake Definitions and check if configuration has changed
CMAKE_DEFINES=""
BUILD_DEFINES=""
CMAKE_CONFIG_CHANGED=0

CMAKE_CHACHE_FILE="$PROJECT_DIR/.build/CMakeCache.txt"

if [ "$CLEAN" == "ON" ]; then
  rm -rf "$PROJECT_DIR/.build"
fi


for OPTION in "${CMAKE_OPTIONS[@]}"; do
  TARGET_VALUE=${!OPTION}
  if [ -f "$CMAKE_CHACHE_FILE" ]; then
      CURRENT_VALUE=$(grep "^${OPTION}:" "$CMAKE_CHACHE_FILE" | cut -d= -f2)
      # compare current value with target value
      if [ "$CURRENT_VALUE" != "$TARGET_VALUE" ]; then
        echo "CMake option $OPTION changed from $CURRENT_VALUE to $TARGET_VALUE"
        CMAKE_CONFIG_CHANGED=1
      fi
  fi
  CMAKE_DEFINES+=" -D$OPTION=$TARGET_VALUE"
done

for OPTION in "${BUILD_OPTIONS[@]}"; do
  TARGET_VALUE=${!OPTION}
  if [ -f "$CMAKE_CHACHE_FILE" ]; then
      CURRENT_VALUE=$(sed -n "s/.*-D${OPTION}=\([^[:space:]]*\).*/\1/p" "$CMAKE_CHACHE_FILE")
      # compare current value with target value
      if [ "$CURRENT_VALUE" != "$TARGET_VALUE" ]; then
        echo "Build option $OPTION changed from $CURRENT_VALUE to $TARGET_VALUE"
        CMAKE_CONFIG_CHANGED=1
      fi
  fi
  BUILD_DEFINES+=" -D$OPTION=$TARGET_VALUE"
done

if [ $CMAKE_CONFIG_CHANGED -eq 1 ]; then
  echo "CMake configuration changed, reconfiguring..."
  rm -rf "$PROJECT_DIR/.build"
fi

if [ ! -d "$PROJECT_DIR/.build" ]; then
  cmake -S . \
        -G Ninja \
        -B $PROJECT_DIR/.build \
        -DCMAKE_C_FLAGS="${BUILD_DEFINES}" \
        ${CMAKE_DEFINES}
fi

cmake --build $PROJECT_DIR/.build --parallel
