#!/usr/bin/env bash
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

# build
$SCRIPT_DIR/build

if [ $? -ne 0 ]; then
  echo "Build failed. Please check the errors."
  exit 1
fi

BIN_DIR="$PROJECT_DIR/.build"

# find elf file from the build output
ELF_FILE=$(find $BIN_DIR -type f -name "*.elf" | head -n 1)

# upload
echo "Uploading firmware"
STM32_Programmer_CLI -c port=SWD -w $ELF_FILE -v -s
